### ISSUE TITLE
Make async-std dependency optional

### ISSUE THREAD

**Issue by sdroege** [async-email/async-native-tls#10]
I'm not sure if this is possible, but it would be great if the async-std dependency could be made optional so that (like async-tls) this could also be used by other runtimes (e.g. the one from glib).

**Comment by dignifiedquire** [comment]
the current version does not use the async-std runtime, it only uses some primitives of it, so it should be runtime agnostic already. I haven’t tested it though

**Comment by sdroege** [comment]
The problem is that it (non-optionally) depends on async-std and brings in a lot of unneeded code (and compile-time) if using it with a different async runtime. Ideally instead of async-std, it would only use whatever is available from the futures crate.

Is there anything used here that is only available in async-std?

**Comment by dignifiedquire** [comment]
> Is there anything used here that is only available in async-std?

yes: https://github.com/async-email/async-native-tls/blob/master/src/acceptor.rs#L60-L61

**Comment by sdroege** [comment]
I see. That makes it rather tricky to make the whole things runtime-independent as you actually depend on async-std :)

**Comment by dignifiedquire** [comment]
Yeah, I guess it could be behind a default feature flag, and the exposed API that is runtime independent could be smaller

**Comment by leo-lb** [comment]
Maybe that solves it? https://github.com/async-email/async-native-tls/pull/14
