### ISSUE TITLE
tests are not compiling

### ISSUE THREAD

**Issue by yoshuawuyts** [async-email/async-native-tls#17]
The `smoke.rs` file is failing. This seems to be a blocker to enable CI as well. Thanks!

**Comment by Nukesor** [comment]
Is this still an issue? I just checked and `cargo test` works perfectly fine on linux stable, nightly and beta.

Which OS do those tests fail on?

**Comment by yoshuawuyts** [comment]
Ah yes a patch was recently merged to address this. Closing!
