### ISSUE TITLE
Connection randomly gives WouldBlock

### ISSUE THREAD

**Issue by pimeys** [async-email/async-native-tls#23]
When connecting to a TLS-enabled server with the crate, and using it together with async-std version 1.6.4 or later, the connection randomly throws an error with a message `"operation would block"`.

This does not happen when using the crate together with async-std 1.6.3 or tokio.

**Comment by hpk42** [comment]
using async-std 1.6.5
I am getting the same problem with Delta chat's core trying to connect (also randomly),

**Comment by link2xt** [comment]
What is the timeout value? Proper way to fix this is to dig down to the code throwing this error and lookup which timeout value it uses.

There is link to documentation saying that wouldblock is an error thrown on connection timeout: https://github.com/deltachat/deltachat-core-rust/issues/1953#issuecomment-701254611

**Comment by stjepang** [comment]
This should be fixed in `async-io` v1.1.6. Can you do `cargo update` and try again?

**Comment by hpk42** [comment]
works fine now for our use.  Closing the issue -- @pimeys please signal if it's still a problem for you.

**Comment by pimeys** [comment]
Works perfect here.
