### ISSUE TITLE
Update to Tokio 1.0

### ISSUE THREAD

**Issue by lsunsi** [async-email/async-native-tls#26]
It's a major first release which the whole ecosystem is supporting, so we should probably follow suit in order to provide better compatibility for lib users. I'm creating this issue so I can link and track from the web3 upgrade issue.

**Comment by FelipeRosa** [comment]
#25

**Comment by wesrer** [comment]
Since this feature has recently been merged, can we push a release to crates.io? That way dependent libraries can start upgrading

**Comment by lclc** [comment]
A new release would be greatly helping dependent libraries.

**Comment by dignifiedquire** [comment]
fixed on master and `0.4.0`
