### ISSUE TITLE
Publish a new release to crates.io?

### ISSUE THREAD

**Issue by PhotonQuantum** [async-email/async-native-tls#31]
It's been a long time since the latest release, and many important improvements have been merged into this crate, namely https://github.com/async-email/async-native-tls/pull/25 (upgrade to tokio 1.0) and https://github.com/async-email/async-native-tls/pull/18 (replace async-std with futures).

Is there any plan for a new release?

**Comment by abel-von** [comment]
I am also looking forward to a new version compatible with tokio 1.0.  I found that tokio is already upgraded to 1.0 on master branch, when will this upgrade publish to crates.io?

**Comment by dignifiedquire** [comment]
Published `0.4.0`.
